import type { Metadata } from "next";
import {
	Geist,
	Geist_Mono,
	Climate_Crisis,
	Noto_Sans_Osage,
} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const climateCrisis = Climate_Crisis({
	variable: "--font-climate-crisis",
	subsets: ["latin"],
  weight: "400",
});

const notoSansOsage = Noto_Sans_Osage({
  variable: "--font-noto-sans-osage",
	subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${climateCrisis.variable} ${notoSansOsage.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
