import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
        <div className="min-h-screen relative overflow-x-hidden">
            <Image
                src="/shape-4.svg"
                width={80}
                height={80}
                alt="rotating shape"
                className="absolute top-0 right-0 w-[800px] h-[800px] animate-[spin_10s_linear_infinite] translate-x-1/2 -translate-y-1/2"
            />
            <div className="max-w-6xl mx-auto px-8">{children}</div>
        </div>
	);
}
