import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div className="min-h-screen flex flex-col justify-center items-center overflow-x-hidden bg-[url('/background-red.svg')] bg-no-repeat bg-cover bg-blend-overlay p-4">
			<div className="max-w-5xl w-full h-full md:h-[600px] flex flex-col justify-center items-center mx-auto font-(family-name:--font-climate-crisis)">
				{children}
			</div>
		</div>
	);
}
